// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ApolloExample: typeof import('./src/components/ApolloExample.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PDFFormsBuilder: typeof import('./src/components/PDFFormsBuilder.vue')['default']
    PdfReader: typeof import('./src/components/PdfReader.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VChip: typeof import('vuetify/lib')['VChip']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VList: typeof import('vuetify/lib')['VList']
    VListGroup: typeof import('vuetify/lib')['VListGroup']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VListItemAvatar: typeof import('vuetify/lib')['VListItemAvatar']
    VListItemContent: typeof import('vuetify/lib')['VListItemContent']
    VListItemIcon: typeof import('vuetify/lib')['VListItemIcon']
    VListItemSubtitle: typeof import('vuetify/lib')['VListItemSubtitle']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMain: typeof import('vuetify/lib')['VMain']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
    VSheet: typeof import('vuetify/lib')['VSheet']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarItems: typeof import('vuetify/lib')['VToolbarItems']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}

export { }
