<template>
  <v-container fluid>
    <v-row>
      <v-col>
        <v-container id="viewerApp" ref="viewerApp" class="pa-0" fluid>
          <viewer ref="viewer" :file="pdf" v-on:loaded="pdfLoaded = true"></viewer>
          <v-footer v-if="pdfLoaded">
            <v-spacer/>
            <v-icon class="mr-3" @click="previusPage">mdi-arrow-left-circle</v-icon>
            <v-icon @click="nextPage">mdi-arrow-right-circle</v-icon>
          </v-footer>
        </v-container>
      </v-col>
      <v-col sm="4">
        <v-responsive :max-height="$refs.viewerApp ? $refs.viewerApp.clientHeight - $refs.newFieldBtn.$el.offsetHeight: 0"
                      class="noScrollbarBG"
                      style="overflow: auto">
          <v-card v-for="(field, key) in fields" v-bind:key="key" class="mb-2" color="other" shaped>
            <v-card-title>
              <v-text-field ref="fieldTitle" :value="field.id" @input="updateTitle(field.id, $event)"/>
            </v-card-title>
            <v-card-subtitle>{{ field.id }}</v-card-subtitle>
            <v-card-text>
              <v-checkbox v-model="field.availableToRepresentative" class="mx-2"
                          label="Disponibile solo al cordinatore"/>
              <v-select :items="fieldTypeNames" :value="fieldTypeNames[$refs.viewer.getFieldById(field.id)[1].type]"/>
            </v-card-text>
            <v-card-actions class="flex-column mx-3 pb-5" style="gap: 10px">
              <v-btn class="mx-0" color="accent" width="100%" @click="moveField(key)">
                <v-icon>mdi-chess-pawn</v-icon>
                <v-spacer/>
                MUOVI IN QUESTA PAGINA
                <v-spacer/>
              </v-btn>
              <v-btn class="mx-0" width="100%" @click="takeMeToId(field.id)">
                <v-icon>mdi-map-marker</v-icon>
                <v-spacer/>
                PORTAMI ALLA PAGINA
                <v-spacer/>
              </v-btn>
              <v-btn class="mx-0" color="error" width="100%" @click="removeField(key)">
                <v-icon>mdi-trash-can</v-icon>
                <v-spacer/>
                RIMUOVI
                <v-spacer/>
              </v-btn>
            </v-card-actions>
          </v-card>
        </v-responsive>
        <v-btn ref="newFieldBtn" color="accent2" width="100%" @click="newField">
          <v-icon>mdi-plus-circle</v-icon>
          <v-spacer/>
          NUOVO FIELD
          <v-spacer/>
        </v-btn>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
import {fabric} from "fabric";
import {fieldTypes, Viewer} from "vue-dreaming-pdf"
import Vue from "vue";
import Component from 'vue-class-component'

export interface field {
  id: string,
  availableToRepresentative: boolean,
}

@Component({
  components: {
    Viewer,
  },
  props: {
    pdf: {
      type: File,
      required: true,
    }
  },
})
export default class Editor extends Vue {
  $refs!: {
    viewer: Viewer
  }

  fields: field[] = []
  pdfLoaded = false

  get fieldTypeNames(): string[] {
    return Object.keys(fieldTypes).map(key => fieldTypes[key]).filter(value => typeof value === 'string');
  }

  newField() {
    let newNumberId: number;

    if (this.fields.length === 0) {
      newNumberId = 0;
    } else {
      newNumberId = Number(this.$refs.viewer.fields.flat().at(-1).id.split("_").at(-1)) + 1;
    }

    const id = `pdp_autogenerated_${newNumberId}`;
    this.fields.push({id, availableToRepresentative: false})
    this.$refs.viewer.addField({
      id,
      type: fieldTypes.Input,
      fabricEntity: new fabric.Text(id, {
        opacity: 0.5,
        backgroundColor: "blue",
        fill: "yellow",
        width: 200,
        height: 100,
        lockRotation: true,
        lockScalingFlip: true,
      })
    });
  }

  takeMeToId(id: string) {
    const page = this.$refs.viewer.getFieldById(id)[0];
    if (page) {
      this.$refs.viewer.setPage(page);
    }
  }

  moveField(index) {
    this.$refs.viewer.moveField(this.fields[index].id, this.$refs.viewer.currentPage);
  }

  removeField(index) {
    this.$refs.viewer.removeField(this.fields[index].id);
    this.fields.splice(index, 1);
  }

  updateTitle(id: string, newTitle: string) {
    if (newTitle == "") {
      newTitle = id;
    }
    this.$refs.viewer.getFieldById(id)[1].fabricEntity.text = newTitle;
    this.$refs.viewer.canvas.requestRenderAll();
  }

  nextPage() {
    this.$refs.viewer.setPage(this.$refs.viewer.currentPage + 1);
  }

  previusPage() {
    this.$refs.viewer.setPage(this.$refs.viewer.currentPage - 1);
  }

  getPDF(): Promise<Uint8Array> {
    return this.$refs.viewer.exportToPDF();
  }
}
</script>

<style lang="scss" scoped>
#viewerApp {
  background-color: var(--v-other1-base);
}
</style>
