<template>
  <v-container fluid>
    <v-row>
      <v-col>
        <v-container ref="viewerApp" fluid class="pa-0" id="viewerApp">
          <viewer v-on:loaded="pdfLoaded = true" ref="viewer" :pdf="pdf"></viewer>
          <v-footer v-if="pdfLoaded">
            <v-spacer/>
            <v-icon @click="previusPage" class="mr-3">mdi-arrow-left-circle</v-icon>
            <v-icon @click="nextPage">mdi-arrow-right-circle</v-icon>
          </v-footer>
        </v-container>
      </v-col>
      <v-col sm="4">
        <v-responsive :max-height="$refs.viewerApp ? $refs.viewerApp.clientHeight - $refs.newFieldBtn.$el.offsetHeight: 0" style="overflow: auto">
          <v-card shaped v-for="(field, key) in fields" v-bind:key="key" color="other" class="mb-2">
            <v-card-title><v-text-field ref="fieldTitle" :value="field"  @input="updateTitle(field, $event)"/></v-card-title>
            <v-card-subtitle>{{field}}</v-card-subtitle>
            <v-card-actions class="flex-column mx-3 pb-5" style="gap: 10px">
              <v-btn color="accent" @click="moveField(key)" class="mx-0" width="100%"><v-icon>mdi-chess-pawn</v-icon><v-spacer/>MUOVI IN QUESTA PAGINA<v-spacer/></v-btn>
              <v-btn @click="takeMeToId(field)" class="mx-0" width="100%"><v-icon>mdi-map-marker</v-icon><v-spacer/>PORTAMI ALLA PAGINA<v-spacer/></v-btn>
              <v-btn @click="removeField(key)" class="mx-0" width="100%" color="error"><v-icon>mdi-trash-can</v-icon><v-spacer/>RIMUOVI<v-spacer/></v-btn>
            </v-card-actions>
          </v-card>
        </v-responsive>
        <v-btn ref="newFieldBtn" @click="newField" width="100%" color="accent2"><v-icon>mdi-plus-circle</v-icon><v-spacer/>NUOVO FIELD<v-spacer/></v-btn>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
import {fabric} from "fabric";
import {Viewer} from "vue-dreaming-pdf"

export default {
  name: "editor",
  components: {
    Viewer
  },
  data() {
    return {
      fields: [],
      pdfLoaded: false,
    }
  },
  methods: {
    newField(){
      const id = `pdp_autogenerated_${this.$refs.viewer.getFieldsLength()}`;
      this.fields.push(id);
      this.$refs.viewer.addField({
        id,
        type: 0,
        fabricEntity: new fabric.Text(id, {
          opacity: 0.5,
          backgroundColor: "blue",
          fill: "yellow",
          width: 200,
          height: 100,
          lockRotation: true,
          lockScalingFlip: true,
        })
      });
    },
    takeMeToId(id: string){
      const page = this.$refs.viewer.getFieldById(id)[0];
      if(page){
        this.$refs.viewer.setPage(page);
      }
    },
    moveField(index){
      this.$refs.viewer.moveField(this.fields[index], this.$refs.viewer.currentPage);
    },
    removeField(index){
      this.$refs.viewer.removeField(this.fields[index]);
      this.fields.splice(index, 1);
    },
    updateTitle(id: string, newTitle: string){
      console.log(newTitle)
      if(newTitle == ""){
        newTitle = id;
      }
      console.log(newTitle)
      this.$refs.viewer.getFieldById(id)[1].fabricEntity.text = newTitle;
      this.$refs.viewer.canvas.requestRenderAll();
    },
    nextPage() {
      this.$refs.viewer.setPage(this.$refs.viewer.currentPage + 1);
    },
    previusPage() {
      this.$refs.viewer.setPage(this.$refs.viewer.currentPage - 1);
    },
    exportPDF() {
      this.$refs.viewer.exportToPDF()
    },
  },
  props: {
    pdf: {
      type: Blob,
      required: true
    }
  },
}
</script>

<style scoped lang="scss">
#viewerApp{
  background-color: var(--v-other1-base);
}
</style>
