<template>
  <v-container fluid>
    <v-row>
      <v-col>
        <v-container ref="viewerApp" fluid class="pa-0" id="viewerApp">
          <viewer v-on:loaded="pdfLoaded = true" ref="viewer" :file="pdf"></viewer>
          <v-footer v-if="pdfLoaded">
            <v-spacer/>
            <v-icon @click="previusPage" class="mr-3">mdi-arrow-left-circle</v-icon>
            <v-icon @click="nextPage">mdi-arrow-right-circle</v-icon>
          </v-footer>
        </v-container>
      </v-col>
      <v-col sm="4">
        <v-responsive class="noScrollbarBG" :max-height="$refs.viewerApp ? $refs.viewerApp.clientHeight - $refs.newFieldBtn.$el.offsetHeight: 0" style="overflow: auto">
          <v-card shaped v-for="(field, key) in fields" v-bind:key="key" color="other" class="mb-2">
            <v-card-title><v-text-field ref="fieldTitle" :value="field.id"  @input="updateTitle(field.id, $event)"/></v-card-title>
            <v-card-subtitle>{{field.id}}</v-card-subtitle>
            <v-card-text>
              <v-checkbox v-model="field.availableToRepresentative" class="mx-2" label="Disponibile solo al rappresentante"/>
              <v-select :value="fieldTypeNames[$refs.viewer.getFieldById(field.id)[1].type]" :items="fieldTypeNames"/>
            </v-card-text>
            <v-card-actions class="flex-column mx-3 pb-5" style="gap: 10px">
              <v-btn color="accent" @click="moveField(key)" class="mx-0" width="100%"><v-icon>mdi-chess-pawn</v-icon><v-spacer/>MUOVI IN QUESTA PAGINA<v-spacer/></v-btn>
              <v-btn @click="takeMeToId(field.id)" class="mx-0" width="100%"><v-icon>mdi-map-marker</v-icon><v-spacer/>PORTAMI ALLA PAGINA<v-spacer/></v-btn>
              <v-btn @click="removeField(key)" class="mx-0" width="100%" color="error"><v-icon>mdi-trash-can</v-icon><v-spacer/>RIMUOVI<v-spacer/></v-btn>
            </v-card-actions>
          </v-card>
        </v-responsive>
        <v-btn ref="newFieldBtn" @click="newField" width="100%" color="accent2"><v-icon>mdi-plus-circle</v-icon><v-spacer/>NUOVO FIELD<v-spacer/></v-btn>
      </v-col>
    </v-row>
  </v-container>
</template>

<script lang="ts">
import {fabric} from "fabric";
import {fieldTypes, Viewer} from "vue-dreaming-pdf"
import Vue from "vue";
import Component from 'vue-class-component'

export interface field {
  id: string,
  availableToRepresentative: boolean,
}

@Component({
  components: {
    Viewer,
  },
  props: {
    pdf: {
      type: File,
      required: true,
    }
  },
})
export default class Editor extends Vue {
  $refs!: {
    viewer: Viewer
  }

  fields: field[] = []
  pdfLoaded = false
  newField(){
    const id = `pdp_autogenerated_${this.$refs.viewer.getFieldsLength()}`;
    this.fields.push({id, availableToRepresentative: false})
    this.$refs.viewer.addField({
      id,
      type: fieldTypes.Input,
      fabricEntity: new fabric.Text(id, {
        opacity: 0.5,
        backgroundColor: "blue",
        fill: "yellow",
        width: 200,
        height: 100,
        lockRotation: true,
        lockScalingFlip: true,
      })
    });
  }
  get fieldTypeNames(): string[]{
    return Object.keys(fieldTypes).map(key => fieldTypes[key]).filter(value => typeof value === 'string');
  }
  takeMeToId(id: string){
    const page = this.$refs.viewer.getFieldById(id)[0];
    if(page){
      this.$refs.viewer.setPage(page);
    }
  }
  moveField(index){
    this.$refs.viewer.moveField(this.fields[index].id, this.$refs.viewer.currentPage);
  }
  removeField(index){
    this.$refs.viewer.removeField(this.fields[index].id);
    this.fields.splice(index, 1);
  }
  updateTitle(id: string, newTitle: string){
    if(newTitle == ""){
      newTitle = id;
    }
    this.$refs.viewer.getFieldById(id)[1].fabricEntity.text = newTitle;
    this.$refs.viewer.canvas.requestRenderAll();
  }
  nextPage() {
    this.$refs.viewer.setPage(this.$refs.viewer.currentPage + 1);
  }
  previusPage() {
    this.$refs.viewer.setPage(this.$refs.viewer.currentPage - 1);
  }
  getPDF(): Promise<Uint8Array>{
    return this.$refs.viewer.exportToPDF();
  }
}
</script>

<style scoped lang="scss">
#viewerApp{
  background-color: var(--v-other1-base);
}
</style>
